### ISSUE TITLE
Check if identifier is already defined

### ISSUE THREAD

**Issue by Eben60** [LilithHafner/BasicAutoloads.jl#16]
Let's assume I define in my startup file
`["plot", "scatter"] => :(using Plots)`
(which is what I'd actually like to do). 

Then I might work with `Makie` in some different context. Now if I call `plot` in the REPL (meaning `Makie.plot`, with `Makie` already imported), `Plots` will be loaded, resulting in a conflict.

**Comment by LilithHafner** [comment]
Sure! You can do that with:
```
["plot", "scatter"] => :(isdefined(Main, :plot) || using Plots)
```
