### ISSUE TITLE
Autoinstall?

### ISSUE THREAD

**Issue by aplavin** [LilithHafner/BasicAutoloads.jl#3]
I wonder if `using SomePackage` executed by BasicAutoloads triggers the base Julia autoinstall prompt?
Like
```julia
julia> using StatsBase
 │ Package StatsBase not found, but a package named StatsBase is available from
 │ a registry. 
 │ Install package?
 │   (@v1.10) pkg> add StatsBase 
 └ (y/n/o) [y]: 
```
Doesn't seem so on the first glance...

This is a very convenient feature to have! See https://gist.github.com/aplavin/cb39121225954e37b6fe8efeebfb6404 for an example & autoload implementation that triggers this prompt.

**Comment by LilithHafner** [comment]
Good feature! I've implemented it as a special case for target exprs of the form `using Blah, Blah, Blah` and `import Blah, Blah, Blah`.

31a92d646f96a150bcbb0484530e486e8e133572

**Comment by LilithHafner** [comment]
Lovely! The hope is to combine all the nice autoload features folks have hacked together into a single easy-to-use place
